### ISSUE TITLE
Incorrect labelling in coef(.)

### ISSUE THREAD

**Issue by rkillick** [JQVeenstra/arfima#2]
If you have an `xreg` argument passed to `arfima` then the labels of the coefficients in `coefs(.)` and `arfima.print` are different.  See example below.

`set.seed(1)
data=arfima.sim(100,model=list(phi=0.5,dfrac=0.4))
fit=arfima(data,xreg=matrix(seq(1850,by=1,len=100),ncol=1))
coef(fit)
fit`

Note that in `coef(fit)` the X1 is -41.9... and in `fit` that is the value of the intercept.

Based on my simulations I believe that `fit` is correct and it is just `coef(fit)` that needs to be changed.

**Comment by JQVeenstra** [comment]
Thanks for the catch!

Fixed.

**Comment by rkillick** [comment]
No problem, always happy to help, just didn't have the time to find the line of code that did it.

**Comment by JQVeenstra** [comment]
And the change has been uploaded to CRAN.  Thanks again!

**Comment by rkillick** [comment]
Thanks for doing this so quickly.  There will be a new dependency for arfima coming to CRAN later this year :-)

**Comment by JQVeenstra** [comment]
My pleasure!

Personally I hate putting things off.  Since I was on my dev machine anyway, and I am the only contributor to this package - I knew where to look.

I am flattered that something's actually going to depend on what amounts to a research package I wrote for my PhD thesis.  I've occasionally tried (a) add some functionality and (b) speed it up, but I rarely find time to do so.
